# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

production:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_polish_ci
  reconnect: false
  database: photoclicker
  pool: 5
  username: root
  password: KKhSbjKKhSbjPmiF7RIq7IleKhGX6ulP!ROWCV$)2xVOy5ec5bdAlgKVQJkPmiF7RIq7IleKhGX6ulbdAlgKVQJk
  socket: /var/run/mysqld/mysqld.sock
  host: localhost

development:
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_polish_ci
  reconnect: false
  database: photoclicker
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
